Changes to allow amber to run from subdirectory

diff --git a/examples/cate_AL_script b/examples/cate_AL_script
--- a/examples/cate_AL_script
+++ b/examples/cate_AL_script
@@ -136,28 +136,35 @@ if true; then
       done
   done
   wait
+fi
+if false; then
   for SP in ${SALL[@]}; do # loop over seeds
       echo Clusters Assemble for $SP initial
       for TT in ${TGS[@]}; do # loop over targets
 	  if [ $SP == ${SALL[NS-1]} ] && [ $TT != ${TALL[0]} ]; then continue; fi
-          # move to clusters directory
-          cd $SP$"_"$IC
-	  # assemble the completed trajectories (do not append log in this case)
-	  # (we must avoid keeping any previous failed attempts to not trigger
-	  # the FAILS check below)
-	  for UU in ${AALL[@]}; do
-	      python ../$scr mlclus $SP $IC"_"$UU | tee $SP"_"$IC"_"$UU"_mlclus_assemble.log"
-	  done
-	  # Clean up DFT directory
-	  if ! grep -q "FAIL"  $SP"_"$IC"_"$UU"_mlclus_assemble.log"; then
-	      rm $DFT"/"*".gbw" $DFT"/"*".cis"
-              tar -czf $DFT".tar.gz" $DFT --remove-files 
-	      rm slurm*
-	  else
-	      FAILS=true
+      # move to clusters directory
+	  if [ -e $SP"_"$IC ]; then
+          cd $SP"_"$IC
+	      # assemble the completed trajectories (write over old log in this case)
+    	  # (we must avoid keeping any previous failed attempts to not trigger
+	      # the FAILS check below)
+          for UU in ${AALL[@]}; do
+              python ../$scr mlclus $SP $IC"_"$UU | tee $SP"_"$IC"_"$UU"_mlclus_assemble.log"
+          done
+          # Clean up DFT directory
+          if ! grep -q "FAIL"  $SP"_"$IC"_"$UU"_mlclus_assemble.log"; then
+              rm $DFT"/"*".gbw" $DFT"/"*".cis"
+                  tar -czf $DFT".tar.gz" $DFT --remove-files 
+              rm slurm*
+          else
+              FAILS=true
               echo "FAILs detected in "$SP"_"$IC"_"$UU"_mlclus_assemble.log"
-	  fi
+    	  fi
           cd $origdir
+      else
+          echo "Folder "$SP"_"$IC" not found"
+	      FAILS=true
+      fi
       done
   done
   if [ "$FAILS" = true ]; then
@@ -187,8 +194,10 @@ if true; then
        echo Setup Training directory for $SA $TT
        X=0 
        python $scr mltrain_setup $SA $TT"_"$W"ac"$X$M"a" | tee -a $SA"_"$TT"_"$W"ac"$X$M"a_mltrain_setup.log"
-       # move script and setup log into folder
-       mv $SA"_"$TT"_"$W"ac"$X$M"a_mltrain_setup.log" $SA"_"$TT"_"$W"ac"$M"_mltrain_sub" $SA"_"$TT"_"$W"ac"
+       # move training script and setup log into folder
+       if [ -d $SA"_"$TT"_"$W"ac" ]; then
+           mv $SA"_"$TT"_"$W"ac"$X$M"a_mltrain_setup.log" $SA"_"$TT"_"$W"ac"$M"_mltrain_sub" $SA"_"$TT"_"$W"ac"
+       fi
        # move test script into folder
        if [ ! -e $SA"_"$TT"_"$W"ac_test" ]; then
           mkdir $SA"_"$TT"_"$W"ac_test"
@@ -240,18 +249,50 @@ do
       cd $origdir
   done
   wait
+  # error check for training (check calculators exist)
+  FAILS=false
+  for TT in ${TALL[@]}; do # loop over states
+      MODELFILES=$SA"_"$TT"_"$W"ac/"$SA"_"$TT"_"$W"ac"$((X-1))$M[a-z]"_stagetwo.model"
+      NMODEL=`echo $MODELFILES | wc -w`
+      if [ ! $NMODEL -eq $C ]; then
+          echo "Not enough final model files found for "$SA" "$TT": "$MODELFILES
+          FAILS=true
+      fi
+  done
+  if [ "$FAILS" = true ]; then
+      echo "Aborting due to previous FAILs"
+      exit
+  fi
+
   # run mltraj with committee of calculators
   for SP in ${SALL[@]}; do # loop over seeds
       echo Trajectories for Generation $X for $SP
       for TT in ${TALL[@]}; do # loop over targets
-	  if [ $SP == ${SALL[NS-1]} ] && [ $TT != ${TALL[0]} ]; then continue; fi
-	  cd $SP"_"$TT"_"$W"ac_mldyn"
+	      if [ $SP == ${SALL[NS-1]} ] && [ $TT != ${TALL[0]} ]; then continue; fi
+	      cd $SP"_"$TT"_"$W"ac_mldyn"
           # submit a mltraj job for each random seed
           sbatch --wait --array=$((X*10))-$((X*10+C-1)) $SP"_"$TT"_"$W"ac"$M"_mltraj_sub" &
-	  cd $origdir
+	      cd $origdir
       done
   done
   wait
+  # error check for mltraj (check mltraj_recalc_carved.traj exists)
+  FAILS=false
+  for SP in ${SALL[@]}; do # loop over seeds
+      for TT in ${TALL[@]}; do # loop over states
+          if [ $SP == ${SALL[NS-1]} ] && [ $TT != ${TALL[0]} ]; then continue; fi
+          TRAJFILES=`ls $SP"_"$TT"_"$W"ac_mldyn/"$SP"_"$TT"_"[A-Z]_$W"ac"$X$M[a-z]"_mldyn_recalc_carved.traj"`
+          NTRAJ=`echo $TRAJFILES | wc -w`
+          if [ ! $NTRAJ -eq $C ]; then
+              echo "Not enough trajectory files  found for "$SP" "$TT": "$TRAJFILES
+              FAILS=true
+          fi
+      done
+  done
+  if [ "$FAILS" = true ]; then
+      echo "Aborting due to previous FAILs"
+      exit
+  fi
   # run mlclus to set up directory and symlinks for clusters run
   for SP in $SA; do # any seed will do here
       echo Clusters Setup for Generation $X for $SP
@@ -269,13 +310,13 @@ do
   for SP in ${SALL[@]}; do # loop over seeds
       echo Clusters Carve for Generation $X for $SP
       for TT in ${TALL[@]}; do # loop over states
-	  if [ $SP == ${SALL[NS-1]} ] && [ $TT != ${TALL[0]} ]; then continue; fi
+	      if [ $SP == ${SALL[NS-1]} ] && [ $TT != ${TALL[0]} ]; then continue; fi
           # move to clusters directory
           cd $SP"_"$TT"_"$W"ac_mlclus"
           # carve the input trajectory
-	  for UU in ${UALL[@]}; do # loop over U and Q
+	      for UU in ${UALL[@]}; do # loop over U and Q
               python ../$scr mlclus_setup $SP $TT"_"$W"ac"$X$M"_"$UU | tee -a $SP"_"$TT"_"$W"ac"$X$M"_"$UU"_mlclus_carve.log"
-           done
+          done
 	  cd $origdir
       done
   done
@@ -285,9 +326,9 @@ do
 	  if [ $SP == ${SALL[NS-1]} ] && [ $TT != ${TALL[0]} ]; then continue; fi
           # move to clusters directory
           cd $SP"_"$TT"_"$W"ac_mlclus"
-	  # submit the cluster jobs for U
+          # submit the cluster jobs for U
           sbatch --wait --array=0-$((NC-1)):$SMAX $SP"_"$TT"_"$W"ac"$X$M"_"${UALL[0]}"_sub" &
-	  cd $origdir
+          cd $origdir
       done
   done
   wait
@@ -295,22 +336,22 @@ do
   for SP in ${SALL[@]}; do # loop over seeds
       echo Clusters Assemble Generation $X for $SP
       for TT in ${TALL[@]}; do # loop over targets
-	  if [ $SP == ${SALL[NS-1]} ] && [ $TT != ${TALL[0]} ]; then continue; fi
+          if [ $SP == ${SALL[NS-1]} ] && [ $TT != ${TALL[0]} ]; then continue; fi
           # move to clusters directory
           cd $SP$"_"$TT"_"$W"ac_mlclus"
-	  # assemble the completed trajectories
-	  for UU in ${UALL[@]}; do
-	      python ../$scr mlclus $SP $TT"_"$W"ac"$X$M"_"$UU | tee -a $SP"_"$TT"_"$W"ac"$X$M"_"$UU"_mlclus_assemble.log"
-	  done
-	  # Clean up DFT directory
-	  if ! grep -q "FAIL"  $SP"_"$TT"_"$W"ac"$X$M"_"$UU$"mlclus_assemble.log"; then
-	      rm $DFT"_ac"$X$M"/"*".gbw" $DFT"_ac"$X$M"/"*".cis"
+          # assemble the completed trajectories
+          for UU in ${UALL[@]}; do
+              python ../$scr mlclus $SP $TT"_"$W"ac"$X$M"_"$UU | tee -a $SP"_"$TT"_"$W"ac"$X$M"_"$UU"_mlclus_assemble.log"
+          done
+          # Clean up DFT directory
+          if ! grep -q "FAIL"  $SP"_"$TT"_"$W"ac"$X$M"_"$UU"_mlclus_assemble.log"; then
+              rm $DFT"_ac"$X$M"/"*".gbw" $DFT"_ac"$X$M"/"*".cis"
               tar -czf $DFT"_ac"$X$M".tar.gz" $DFT"_ac"$X$M --remove-files 
-	      rm slurm*
-	  else
-	      FAILS=true
+              rm slurm*
+          else
+              FAILS=true
               echo "FAILs detected in "$SP"_"$TT"_"$W"ac"$X$M"_"$UU"_mlclus_assemble.log"
-	  fi
+          fi
           cd $origdir
       done
   done
